"""empty message

Revision ID: a8edca44553c
Revises: ea441bb3ee4f
Create Date: 2024-04-26 12:07:58.053297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8edca44553c'
down_revision: Union[str, None] = 'ea441bb3ee4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('create_at', sa.DateTime(), nullable=False))
    op.drop_column('atletas', 'created_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('created_data', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('atletas', 'create_at')
    # ### end Alembic commands ###
